spring:
  profiles:
    active: dev
  # 当出现404的时候，默认是不抛异常的，而是 forward跳转到/error控制器(BasicErrorController), 添加如下配置 可以取消默认的跳转
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
