# 端口号
server:
  port: 8083

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/nba?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定使用 Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始化时建立物理连接的个数
      max-active: 20 # 最大的连接池数量
      min-idle: 5 # 最小链接池数量
      max-wait: 3000 # 获取连接时最大等待时间，单位毫秒
      # 是否缓存preparedStatement，也就是PSCache, PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: -1
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 400000

# 日志相关
logging:
  level.root: info
  level.org.elasticsearch: trace
  level.com.zbcn.combootes.nba.service: trace



# elasticSearch 配置
elasticsearch:
  schema: http
  address: 47.99.133.237:9200
  user_name: elastic
  password: 123456
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100