spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # 解决bean 的重复注入问题
  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis

#\u5F00\u542FMybatis\u4E0B\u5212\u7EBF\u547D\u540D\u8F6C\u9A7C\u5CF0\u547D\u540D
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# session 过期时间，单位：秒
server:
  servlet:
    session:
      timeout: 60