
server:
  port: 8001
## producer配置
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: 123456
    virtual-host: dev # 虚拟host 可以不设置,使用server默认host
    publisher-returns: true #返回确认
    template:
      mandatory: true
    publisher-confirm-type: correlated
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  type-aliases-package: com.zbcn.common.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map 空列不显示问题
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.javayh.dao: DEBUG