# 邮件相关
# SMTP服务器地址
spring:
  mail:
    host: smtp.qq.com
    port: -1 # SMTP服务器端口号 默认-1
    username: 1363653611@qq.com
    password: yohkywkznmjigjaj # 发送方密码（授权码）

    #javaMailProperties 配置
    # 开启用户身份验证
    properties:
      mail:
        smtp:
          auth: true
    # STARTTLS：一种通信协议，具体可以搜索下
    #spring.mail.properties.mail.smtp.starttls.enable=true
    #spring.mail.properties.mail.smtp.starttls.required=true


  freemarker:
    # 缓存配置 开发阶段应该配置为false 因为经常会改
    cache: false
    # 模版后缀名 默认为ftl
    suffix: .ftl
    # 文件编码
    charset: UTF-8
    # 模版加载的目录
    template-loader-path: classpath:/templates/
