spring:
  application:
    name: javayh-redis
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password:

#1、单机模式
redisson:
  address: redis://localhost:6379
  #redisson.password=
  master-name: mymaster
  sentinel-addresses: localhost:26379,10.47.91.83:26380,10.47.91.83:26381 # 哨兵模式


