spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # \u53EF\u9009
    druid:
      initial-size: 5
      max-active: 20  # maxPoolSize
      min-idle: 5 # minPoolSize
      #\u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      max-wait: 60000
      # \u6821\u9A8C
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #\u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      time-between-eviction-runs-millis: 60000
      #\u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      min-evictable-idle-time-millis: 300000

  #jpa\u76F8\u5173\u914D\u7F6E
  # \u663E\u793Asql \u4F46\u4E0D\u4F1A\u663E\u793A\u5177\u4F53\u7684\u64CD\u4F5C\u503C \u53EF\u4EE5\u66FF\u6362\u6210log4jdbc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization: true



