spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# mybatis 相关配置
mybatis:
  # xml配置的在java package中，而Spring Boot默认只打入java package -> *.java，所以我们需要给pom.xml 添加打 .xml 的配置
  # mapper-locations: classpath:com/zbcn/combootmybatis/mapper/*.xml
  mapper-locations: classpath:mapper/*.xml #这种方式需要自己在resources目录下创建mapper目录然后存放xml
  type-aliases-package: com.zbcn.combootmybatis.entity
  configuration:
    # mybatis.configuration.map-underscore-to-camel-case是一个非常好的配置项，合理的命名规范可以让我们省略很多不必要的麻烦，比如xx-mapper.xml中的resultMap的映射可以省略掉了
    map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId

########## 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  enum-as-simple-type: true # 枚举按简单类型处理

########## 分页插件 ##########
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  # 分页合理化参数，默认值为false.当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: false
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true

# 如果想看到mybatis日志需要做如下配置
logging:
  level:
    com.zbcn.combootmybatis: DEBUG